rm -rf download
mkdir download

wget http://api.bitcoincharts.com/v1/csv/1coinUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/abucoinsEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/abucoinsPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/abucoinsUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/allcoinUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkCHF.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkCNY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkHKD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkNZD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkSGD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/anxhkUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/aqoinEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/b2cUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/b7EUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/b7USD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bbmBRL.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcmBMAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcmBMGAU.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcmBMUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcmLRUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcmMBUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcmMLUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcmPPUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcmPXGAU.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bcnorwayNOK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bidxtrmPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bit121GBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bit2cILS.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitaloCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitaloEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitaloGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitaloPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitaloUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitbayEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitbayPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitbayUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitboxUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitcashCZK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitchangePLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitcurexEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitcurexPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitcurexUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitfinexUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitfloorUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitflyerJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitkonanUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmarketAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmarketEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmarketGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmarketPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmarketRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmarketUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmarketplPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmaszynaPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmeLTC.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitmeUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitnzNZD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitomatPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitsoMXN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitstampEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitstampUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitstockCZK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitxIDR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitxMYR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitxNGN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/bitxZAR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/britcoinGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btc24EUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btc24USD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btc2uBRL.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcalphaUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcboxJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btccUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcdeEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btceEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btceRUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btceUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btceurEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcexEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcexJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcexRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcexUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcexWMR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcexWMZ.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcexYAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btchkexHKD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcmarketsAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcnCNY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcoidIDR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btctradeCNY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btctreeUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcxEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcxUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/btcxchangeRON.csv.gz
wget http://api.bitcoincharts.com/v1/csv/cbxUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/cexEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/cexRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/cexUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/chbtcCNY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/chilebitCLP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinbaseCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinbaseEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinbaseGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinbaseUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coincheckJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinfalconEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinfloorGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinnestKRW.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinsbankEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinsbankGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinsbankRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/coinsbankUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/cotrUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/cryptoxAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/cryptoxUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/crytrEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/crytrUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/exchbUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/exmoEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/exmoRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/exmoUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/fbtcEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/fbtcUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/fiscoJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/fluctoPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/foxbitBRL.csv.gz
wget http://api.bitcoincharts.com/v1/csv/freshEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/freshPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/freshUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/fybseSEK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/fybsgSGD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/getbtcUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/globalEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/globalGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/globalPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/globalUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/hitbtcEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/hitbtcUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ibwtEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ibwtGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ibwtLTC.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ibwtUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/icbitUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/imcexEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/imcexRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/imcexUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/indacoinUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/intrsngEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/intrsngGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/intrsngPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/intrsngUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/itbitEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/itbitSGD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/itbitUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/jubiCNY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/justEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/justLTC.csv.gz
wget http://api.bitcoincharts.com/v1/csv/justNOK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/justUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/justXRP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/korbitKRW.csv.gz
wget http://api.bitcoincharts.com/v1/csv/kptnSEK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/krakenCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/krakenEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/krakenGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/krakenJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/krakenKRW.csv.gz
wget http://api.bitcoincharts.com/v1/csv/krakenLTC.csv.gz
wget http://api.bitcoincharts.com/v1/csv/krakenNMC.csv.gz
wget http://api.bitcoincharts.com/v1/csv/krakenUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/krakenXRP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/lakeUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcARS.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcBRL.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcCHF.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcCZK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcDKK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcHKD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcILS.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcINR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcMXN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcNOK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcNZD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcSEK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcSGD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcTHB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcVEF.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcVND.csv.gz
wget http://api.bitcoincharts.com/v1/csv/localbtcZAR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/lybitCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/lybitUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mrcdBRL.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxCHF.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxCNY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxDKK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxHKD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxNOK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxNZD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxSEK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxSGD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxTHB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/mtgoxUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/nevbitPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/okcoinUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/remitanoVND.csv.gz
wget http://api.bitcoincharts.com/v1/csv/rippleEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/rippleUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/rippleXRP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/rmbtbCNY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/rockEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/rockSLL.csv.gz
wget http://api.bitcoincharts.com/v1/csv/rockUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumCHF.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumHKD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumHUF.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumSEK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumSGD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumTHB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumUAH.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/ruxumZAR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/snwcnXRP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/surbtcVEF.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thARS.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thBRL.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thCHF.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thCLP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thCNY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thCZK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thDKK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thGBP.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thHKD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thILS.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thINR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thLRUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thMXN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thNOK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thNZD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thPEN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thPLN.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thSEK.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/thZAR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/urdubitPKR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/vbtcVND.csv.gz
wget http://api.bitcoincharts.com/v1/csv/vcxEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/vcxUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/virtexCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/virwoxSLL.csv.gz
wget http://api.bitcoincharts.com/v1/csv/wbxAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/weexAUD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/weexCAD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/weexUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/wexEUR.csv.gz
wget http://api.bitcoincharts.com/v1/csv/wexRUB.csv.gz
wget http://api.bitcoincharts.com/v1/csv/wexUSD.csv.gz
wget http://api.bitcoincharts.com/v1/csv/zaifJPY.csv.gz
wget http://api.bitcoincharts.com/v1/csv/zyadoEUR.csv.gz

mv *.csv.gz download
